name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /pubgresource

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
            lfs: 'true'
            submodules: 'true'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
      - name: Install Git LFS
        run: |
          git lfs install
          git lfs fetch --all
      - name: Install submodules
        run: |
          git submodule update --init --recursive
      - name: Debug
        run: |
          ls -l submodules
          ls -l submodules/pubg
          ls -l submodules/pubg/api-assets
          ls -l submodules/pubg/api-assets/Assets    
      - name: Copy submodule assets
        run: |
          mkdir -p public/img/pubg
          cp -R submodules/pubg/api-assets/Assets/ public/img/pubg
      - name: Build project
        run: npm run build
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: out
          clean: true